### ISSUE TITLE
Does not work in Hybrid App

### ISSUE THREAD

**Issue by melvingrootenboers** [synobsys/mendix-DragAndDropSupportWidget#1]
It is not possible to drag and drop an item in the Hybrid App (iOS and Android).

**Comment by mgroeneweg** [comment]
There was an issue with the jQuery libraries in the first release. I recreated the first release. Please try with the updated widget mpk file. It works for me with the test project in the Mendix Developer App

**Comment by melvingrootenboers** [comment]
I have retested it with the latest version and it works fine.

**Comment by mgroeneweg** [comment]
Great!
