### ISSUE TITLE
Support for nested lists

### ISSUE THREAD

**Issue by ppoetsma** [synobsys/mendix-DragAndDropSupportWidget#2]
Hi,

I am experimenting with your widget and I am wondering if nested lists are supported. At the top level I create a list of groups using drag and drop. Next I want to add items to these groups, also via drag and drop. Is that possible?

I gave it a try and the group object that is provided to the microflow is always the last group, not the group that I dropped the item on.

Regards,
Paul

**Comment by mgroeneweg** [comment]
You would need two droppable widgets, each with a separate accept CSS class. Specify those classes on the items you want to drag. This ensures that an item is dragged on the right container.

**Comment by ppoetsma** [comment]
Took a while to try it but it works. Takes some time to understand how it works, but it works. Thanks.

**Comment by mgroeneweg** [comment]
Good to hear that it works for you.
